# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"

[version]
current = "0.12.1"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump version: 0.12.1 to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "tbump.toml"
search = '{current_version}'

[[file]]
src = "setup.py"
search = 'version="{current_version}"'

[[file]]
src = "openwind/__init__.py"
search = '__version__ = "{current_version}"'

[[file]]
src = "meta.yaml"
search = 'set version = "{current_version}"'

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "pyproject.toml"
search = 'Download = "https://gitlab.inria.fr/openwind/openwind/-/archive/v{current_version}/openwind-v{current_version}.zip"'

[[file]]
src = "codemeta.json"
search = '"version": "{current_version}"'

[[file]]
src = "codemeta.json"
search = '"downloadUrl": "https://gitlab.inria.fr/openwind/openwind/-/archive/v{current_version}/openwind-v{current_version}.zip",'

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
name = "update codemeta"
cmd = "python docs/update_codemeta.py"

[[before_commit]]
name = "update changelog"
cmd = "python docs/update_changelog.py {new_version}"

# [[before_commit]]
# name = "clean changelog"
# cmd = "printf '### Changed' > docs/latest_changelog.md"

# [[before_commit]]
# name = "update documentation how-to"
# cmd = "python docs/update_howto.py"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
